package ec.edu.ups.pweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:05:06.679-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://serviceSOAP.EVAPizarroJorgeSVR.pweb.ups.edu.ec/", name = "ServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "getObras", targetNamespace = "http://serviceSOAP.EVAPizarroJorgeSVR.pweb.ups.edu.ec/", className = "ec.edu.ups.pweb.GetObras")
    @ResponseWrapper(localName = "getObrasResponse", targetNamespace = "http://serviceSOAP.EVAPizarroJorgeSVR.pweb.ups.edu.ec/", className = "ec.edu.ups.pweb.GetObrasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.pweb.Obra> getObras()
;

    @WebMethod
    @RequestWrapper(localName = "insertarObra", targetNamespace = "http://serviceSOAP.EVAPizarroJorgeSVR.pweb.ups.edu.ec/", className = "ec.edu.ups.pweb.InsertarObra")
    @ResponseWrapper(localName = "insertarObraResponse", targetNamespace = "http://serviceSOAP.EVAPizarroJorgeSVR.pweb.ups.edu.ec/", className = "ec.edu.ups.pweb.InsertarObraResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean insertarObra(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.pweb.Obra arg0
    );
}
